### ISSUE TITLE
After the 2.3.0 upgrade Cloudformation gives an error when deplying new server

### ISSUE THREAD

**Issue by olzzon** [OpenVidu/openvidu-cloud-devops#3]
When I deploy a new server using:
https://openvidu.io/docs/deployment/deploying-aws/

I get the following error:
Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user.
--

I did 4 deploys last week with no problems, but when I tried yesterday I got this error.
(I tried selfsigned and LetsEncrypt both gives the same error)

Has it something to do with the new 2.3.0?

**Comment by olzzon** [comment]
Yep, my fault, sorry for wasting your time 👍

**Comment by nordri** [comment]
Happy to help!
