### ISSUE TITLE
auto renew lets encrypt

### ISSUE THREAD

**Issue by rush86999** [OpenVidu/openvidu-cloud-devops#7]
Hello,

 Is there a way to auto-renew let's encrypt instances? Or what is the process to renew? Any links or tutorial would be helpful using this EC2 instance.

**Comment by nordri** [comment]
It's supposed to be automatically updated. 
If not you can follow this manual:
https://community.letsencrypt.org/t/renew-letsencrypt-certificate/34677

Let me know if you need more information.
Cheers!

**Comment by rush86999** [comment]
ok thanks, I was thinking in advance
