### ISSUE TITLE
How can I update the PORT output?

### ISSUE THREAD

**Issue by Khangdv6669** [OpenVidu/openvidu-cloud-devops#8]
Hi @nordri. 
As I see the output alway be 4443. https://github.com/OpenVidu/openvidu-cloud-devops/blob/master/cloudformation-openvidu/CF-OpenVidu-TEMPLATE.yaml
Could I change the output PORT? If yes, How can I do it?
Thanks you.

**Comment by nordri** [comment]
Hi @Khangdv6669 
Nowadays, it is not possible to change the port, I'm sorry.
We'll save this issue for future releases to allow users to use custom ports.
Have a nice day.
