### ISSUE TITLE
CloudFormation Import Error

### ISSUE THREAD

**Issue by bowersz** [OpenVidu/openvidu-cloud-devops#9]
Hello,

I'm attempting to import the Cloud Formation stack form the template using the url that is listed in the tutorial, but am getting an error on the import. Is the S3 link up to date?

Thanks!
<img width="1121" alt="Screen Shot 2020-02-03 at 10 30 37 PM" src="https://user-images.githubusercontent.com/13421507/73711497-0c814c00-46d5-11ea-9f22-f662e752ea31.png">

**Comment by pabloFuente** [comment]
AWS documentation says that "importing" CF templates is only supported for very specific resources: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

You aren't supposed to import the template into an existing stack. You are supposed to deploy a new one from scratch, as OpenVidu docs states.

Regards.
